2010-05-02 Niall Power - <niall.power@oracle.com>
        * lib/svc/method/time-slider:
          Remove any legacy zfs-auto-snapshot cron jobs in
          zfssnap's crontab that may not have been removed
          if the old auto-snapshot services were not stopped
          cleanly.

diff --git a/lib/svc/method/time-slider b/lib/svc/method/time-slider
--- a/lib/svc/method/time-slider
+++ b/lib/svc/method/time-slider
@@ -27,8 +27,57 @@
 
 . /lib/svc/share/smf_include.sh
 
+
+# Given the exit status of a command, an integer, 0 if the command completed
+# without errors. If the command exited with errors we degrade the
+# state of this service into maintenance mode. If a 3rd argument is presented
+# we don't degrade the service. We also log an error message as passed into
+# this function.
+#
+function check_failure { # integer exit status, error message, non-fatal flag
+
+	typeset RESULT=$1
+	typeset ERR_MSG=$2
+	typeset NON_FATAL=$3
+
+	if [ $RESULT -ne 0 ] ; then
+	    print_log "Error: $ERR_MSG"
+	    if [ -z "${NON_FATAL}" ] ; then
+		print_log "Moving service $SMF_FMRI to maintenance mode."
+	        svcadm mark maintenance $SMF_FMRI
+	    fi
+	fi
+
+}
+
+
+# A function we use to emit output. Right now, this goes to syslog via logger(1)
+# as well as being echoed to stdout which will result in it being picked up by
+# SMF if the $LOG variable is null.
+#
+function print_log { # message to display
+	logger -t time-slider -p daemon.notice $*
+	echo $*
+}
+
+# this function removes any left over cron jobs belonging to
+# legacy zfs-auto-snapshot
+#
+function remove_legacy_cronjobs {
+
+	crontab -l | grep -v "/lib/svc/method/zfs-auto-snapshot" \
+	    > /tmp/saved-crontab.$$
+
+	crontab /tmp/saved-crontab.$$
+	check_failure $? "Unable to remove legacy zfs-auto-snaphot cron jobs" "NON_FATAL"
+
+	rm /tmp/saved-crontab.$$
+
+}
+
 case "$1" in
 'start')
+	remove_legacy_cronjobs
 
 	[ ! -x /usr/lib/time-sliderd ] && exit $SMF_EXIT_ERR_CONFIG
 
